### ISSUE TITLE
new code file is all about

### ISSUE THREAD

**Issue by Gamelife311** [sais999/UAV-path-planning-algorithm#1]
Hello, can you explain what your new code file is all about

**Comment by sais999** [comment]
you can now see the full code of the project in the repository. Save a graph using the scripts I have created then run each of the three algorithms and see them working for yourself. The best algorithm of the three is the new algorithm that I am proposing which is called APPATrectangles, I take inspiration from the APPATT algorithm but I model the obstacles as rectangles instead of ellipses.

**Comment by Gamelife311** [comment]
> you can now see the full code of the project in the repository. Save a graph using the scripts I have created then run each of the three algorithms and see them working for yourself. The best algorithm of the three is the new algorithm that I am proposing which is called APPATrectangles, I take inspiration from the APPATT algorithm but I model the obstacles as rectangles instead of ellipses.

Thank you very much for your answer
